"""product_price

Revision ID: 6cfb551887c3
Revises: 8983c1db0b95
Create Date: 2026-01-13 19:44:38.044694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfb551887c3'
down_revision = '8983c1db0b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bids', 'user', ['user_id'], ['id'])
    op.add_column('product', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.drop_constraint(None, 'bids', type_='foreignkey')
    # ### end Alembic commands ###
